import { McpServer } from "@modelcontextprotocol/server";
import { z } from "zod";

const DIRECT_TIMEOUT_MS = 15_000;
const APIFY_TIMEOUT_MS = 55_000;
const DEFAULT_MAX_CHARACTERS = 120_000;
const HARD_MAX_CHARACTERS = 200_000;
const APIFY_ACTOR_ID = "apidojo~youtube-transcript-scraper";
const APIFY_MAX_TOTAL_CHARGE_USD = "0.01";

export type VideoEnv = {
  APIFY_TOKEN?: string;
};

type CaptionTrack = {
  baseUrl?: string;
  languageCode?: string;
  kind?: string;
  name?: {
    simpleText?: string;
    runs?: Array<{ text?: string }>;
  };
};

type TranscriptSegment = {
  start: number;
  duration: number;
  text: string;
};

type TranscriptSuccess = {
  ok: true;
  source: "youtube";
  videoId: string;
  provider: string;
  language: string | null;
  isAutoGenerated: boolean | null;
  text: string;
  segments?: TranscriptSegment[];
  totalCharacters: number;
  truncated: boolean;
};

type TranscriptFailure = {
  ok: false;
  source: "youtube";
  videoId?: string;
  provider: string;
  code:
    | "INVALID_URL"
    | "NO_TRANSCRIPT"
    | "YOUTUBE_BLOCKED"
    | "UPSTREAM_TIMEOUT"
    | "UPSTREAM_UNAVAILABLE"
    | "UPSTREAM_PROTOCOL_ERROR"
    | "APIFY_AUTH_REQUIRED";
  message: string;
  fallbackAttempted?: boolean;
};

function timedFetch(input: RequestInfo | URL, init: RequestInit, timeoutMs: number): Promise<Response> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort("video transcript timeout"), timeoutMs);
  return fetch(input, { ...init, signal: controller.signal }).finally(() => clearTimeout(timer));
}

export function parseYoutubeVideoId(input: string): string | null {
  const raw = input.trim();
  if (/^[A-Za-z0-9_-]{11}$/.test(raw)) return raw;

  let url: URL;
  try {
    url = new URL(raw);
  } catch {
    return null;
  }

  const host = url.hostname.toLowerCase().replace(/^www\./, "");
  let candidate: string | null = null;

  if (host === "youtu.be") {
    candidate = url.pathname.split("/").filter(Boolean)[0] ?? null;
  } else if (host === "youtube.com" || host === "m.youtube.com" || host === "music.youtube.com") {
    if (url.pathname === "/watch") candidate = url.searchParams.get("v");
    else {
      const parts = url.pathname.split("/").filter(Boolean);
      if (["shorts", "embed", "live"].includes(parts[0] ?? "")) candidate = parts[1] ?? null;
    }
  }

  return candidate && /^[A-Za-z0-9_-]{11}$/.test(candidate) ? candidate : null;
}

function extractBalancedObject(text: string, start: number): string | null {
  const first = text.indexOf("{", start);
  if (first < 0) return null;

  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let i = first; i < text.length; i += 1) {
    const char = text[i];
    if (inString) {
      if (escaped) escaped = false;
      else if (char === "\\") escaped = true;
      else if (char === '"') inString = false;
      continue;
    }

    if (char === '"') inString = true;
    else if (char === "{") depth += 1;
    else if (char === "}") {
      depth -= 1;
      if (depth === 0) return text.slice(first, i + 1);
    }
  }
  return null;
}

function extractPlayerResponse(html: string): Record<string, unknown> | null {
  const markers = [
    "ytInitialPlayerResponse =",
    "var ytInitialPlayerResponse =",
    '"ytInitialPlayerResponse":',
  ];

  for (const marker of markers) {
    const index = html.indexOf(marker);
    if (index < 0) continue;
    const jsonText = extractBalancedObject(html, index + marker.length);
    if (!jsonText) continue;
    try {
      return JSON.parse(jsonText) as Record<string, unknown>;
    } catch {
      // Try the next representation.
    }
  }
  return null;
}

function trackName(track: CaptionTrack): string {
  if (track.name?.simpleText) return track.name.simpleText;
  return (track.name?.runs ?? []).map((run) => run.text ?? "").join("").trim();
}

export function selectCaptionTrackForTest(
  tracks: CaptionTrack[],
  language?: string,
): CaptionTrack | null {
  if (!tracks.length) return null;
  const preferred = language?.trim().toLowerCase();

  const rank = (track: CaptionTrack): number => {
    const code = track.languageCode?.toLowerCase() ?? "";
    const manualPenalty = track.kind === "asr" ? 10 : 0;
    if (!preferred) return manualPenalty;
    if (code === preferred) return manualPenalty;
    if (code.split("-")[0] === preferred.split("-")[0]) return 2 + manualPenalty;
    return 100 + manualPenalty;
  };

  return [...tracks].sort((a, b) => rank(a) - rank(b))[0] ?? null;
}

export function parseJson3TranscriptForTest(payload: unknown): TranscriptSegment[] {
  if (!payload || typeof payload !== "object") return [];
  const events = (payload as { events?: unknown[] }).events;
  if (!Array.isArray(events)) return [];

  const segments: TranscriptSegment[] = [];
  for (const event of events) {
    if (!event || typeof event !== "object") continue;
    const record = event as {
      tStartMs?: number;
      dDurationMs?: number;
      segs?: Array<{ utf8?: string }>;
    };
    if (!Array.isArray(record.segs)) continue;
    const text = record.segs
      .map((segment) => segment.utf8 ?? "")
      .join("")
      .replace(/\s+/g, " ")
      .trim();
    if (!text) continue;
    segments.push({
      start: Math.max(0, Number(record.tStartMs ?? 0) / 1000),
      duration: Math.max(0, Number(record.dDurationMs ?? 0) / 1000),
      text,
    });
  }
  return segments;
}

function capTranscript(
  segments: TranscriptSegment[],
  maxCharacters: number,
): { text: string; segments: TranscriptSegment[]; totalCharacters: number; truncated: boolean } {
  const fullText = segments.map((segment) => segment.text).join(" ").replace(/\s+/g, " ").trim();
  const totalCharacters = fullText.length;
  if (totalCharacters <= maxCharacters) {
    return { text: fullText, segments, totalCharacters, truncated: false };
  }

  let used = 0;
  const kept: TranscriptSegment[] = [];
  for (const segment of segments) {
    const extra = segment.text.length + (kept.length ? 1 : 0);
    if (used + extra > maxCharacters) break;
    kept.push(segment);
    used += extra;
  }

  return {
    text: fullText.slice(0, maxCharacters),
    segments: kept,
    totalCharacters,
    truncated: true,
  };
}

function captionTracksFromPlayerResponse(player: Record<string, unknown>): CaptionTrack[] {
  const captions = player.captions as
    | { playerCaptionsTracklistRenderer?: { captionTracks?: CaptionTrack[] } }
    | undefined;
  return captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
}

async function directYoutubeTranscript(
  originalUrl: string,
  videoId: string,
  language: string | undefined,
  maxCharacters: number,
): Promise<TranscriptSuccess | TranscriptFailure> {
  const watchUrl = "https://www.youtube.com/watch?v=" + encodeURIComponent(videoId) + "&hl=en&gl=US";
  let response: Response;
  try {
    response = await timedFetch(
      watchUrl,
      {
        headers: {
          "User-Agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/140.0.0.0 Safari/537.36",
          "Accept-Language": "en-US,en;q=0.9",
        },
      },
      DIRECT_TIMEOUT_MS,
    );
  } catch (error) {
    const timedOut = error instanceof Error && /abort|timeout/i.test(error.message + " " + error.name);
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "youtube-captions-direct",
      code: timedOut ? "UPSTREAM_TIMEOUT" : "UPSTREAM_UNAVAILABLE",
      message: timedOut ? "YouTube did not respond before the transcript timeout." : "YouTube watch page could not be fetched.",
    };
  }

  if (response.status === 403 || response.status === 429) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "youtube-captions-direct",
      code: "YOUTUBE_BLOCKED",
      message: "YouTube blocked the transcript request from the current network.",
    };
  }
  if (!response.ok) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "youtube-captions-direct",
      code: "UPSTREAM_UNAVAILABLE",
      message: "YouTube returned HTTP " + response.status + ".",
    };
  }

  const html = await response.text();
  if (/unusual traffic|verify you are not a bot|consent\.youtube/i.test(html)) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "youtube-captions-direct",
      code: "YOUTUBE_BLOCKED",
      message: "YouTube returned a bot or consent interstitial instead of the video page.",
    };
  }

  const player = extractPlayerResponse(html);
  if (!player) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "youtube-captions-direct",
      code: "UPSTREAM_PROTOCOL_ERROR",
      message: "The YouTube player response could not be located in the page.",
    };
  }

  const tracks = captionTracksFromPlayerResponse(player);
  if (!tracks.length) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "youtube-captions-direct",
      code: "NO_TRANSCRIPT",
      message: "This video exposes no caption track.",
    };
  }

  const track = selectCaptionTrackForTest(tracks, language);
  if (!track?.baseUrl) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "youtube-captions-direct",
      code: "UPSTREAM_PROTOCOL_ERROR",
      message: "YouTube exposed a caption track without a usable URL.",
    };
  }

  const captionUrl = new URL(track.baseUrl);
  captionUrl.searchParams.set("fmt", "json3");

  let captionResponse: Response;
  try {
    captionResponse = await timedFetch(
      captionUrl,
      {
        headers: {
          "User-Agent":
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/140.0.0.0 Safari/537.36",
          Referer: originalUrl,
        },
      },
      DIRECT_TIMEOUT_MS,
    );
  } catch (error) {
    const timedOut = error instanceof Error && /abort|timeout/i.test(error.message + " " + error.name);
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "youtube-captions-direct",
      code: timedOut ? "UPSTREAM_TIMEOUT" : "UPSTREAM_UNAVAILABLE",
      message: timedOut ? "YouTube captions timed out." : "YouTube captions could not be fetched.",
    };
  }

  if (!captionResponse.ok) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "youtube-captions-direct",
      code: captionResponse.status === 403 || captionResponse.status === 429 ? "YOUTUBE_BLOCKED" : "UPSTREAM_UNAVAILABLE",
      message: "YouTube caption endpoint returned HTTP " + captionResponse.status + ".",
    };
  }

  let payload: unknown;
  try {
    payload = await captionResponse.json();
  } catch {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "youtube-captions-direct",
      code: "UPSTREAM_PROTOCOL_ERROR",
      message: "YouTube captions were not valid JSON3.",
    };
  }

  const segments = parseJson3TranscriptForTest(payload);
  if (!segments.length) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "youtube-captions-direct",
      code: "NO_TRANSCRIPT",
      message: "The selected caption track contained no transcript text.",
    };
  }

  const capped = capTranscript(segments, maxCharacters);
  return {
    ok: true,
    source: "youtube",
    videoId,
    provider: "youtube-captions-direct",
    language: track.languageCode ?? null,
    isAutoGenerated: track.kind === "asr",
    text: capped.text,
    segments: capped.segments,
    totalCharacters: capped.totalCharacters,
    truncated: capped.truncated,
  };
}

function normalizeApifySegments(item: Record<string, unknown>): TranscriptSegment[] {
  const raw = Array.isArray(item.transcript)
    ? item.transcript
    : Array.isArray(item.segments)
      ? item.segments
      : [];
  const result: TranscriptSegment[] = [];

  for (const entry of raw) {
    if (!entry || typeof entry !== "object") continue;
    const row = entry as Record<string, unknown>;
    const text = String(row.text ?? row.utf8 ?? "").replace(/\s+/g, " ").trim();
    if (!text) continue;
    const start = Number(row.start ?? row.offset ?? row.startTime ?? 0);
    const duration = Number(row.duration ?? row.dur ?? 0);
    result.push({
      start: Number.isFinite(start) ? start : 0,
      duration: Number.isFinite(duration) ? duration : 0,
      text,
    });
  }
  return result;
}

async function apifyTranscriptFallback(
  env: VideoEnv,
  originalUrl: string,
  videoId: string,
  language: string | undefined,
  maxCharacters: number,
): Promise<TranscriptSuccess | TranscriptFailure> {
  const token = env.APIFY_TOKEN?.trim();
  if (!token) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "apify:" + APIFY_ACTOR_ID,
      code: "APIFY_AUTH_REQUIRED",
      message: "Direct YouTube caption access failed and APIFY_TOKEN is not configured for the fallback.",
      fallbackAttempted: false,
    };
  }

  const endpoint =
    "https://api.apify.com/v2/actors/" +
    APIFY_ACTOR_ID +
    "/run-sync-get-dataset-items?format=json&clean=true&limit=1&maxItems=1&maxTotalChargeUsd=" +
    APIFY_MAX_TOTAL_CHARGE_USD;

  let response: Response;
  try {
    response = await timedFetch(
      endpoint,
      {
        method: "POST",
        headers: {
          Authorization: "Bearer " + token,
          "Content-Type": "application/json",
          Accept: "application/json",
        },
        body: JSON.stringify({
          startUrls: [originalUrl],
          ...(language ? { lang: language } : {}),
          maxItems: 1,
        }),
      },
      APIFY_TIMEOUT_MS,
    );
  } catch (error) {
    const timedOut = error instanceof Error && /abort|timeout/i.test(error.message + " " + error.name);
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "apify:" + APIFY_ACTOR_ID,
      code: timedOut ? "UPSTREAM_TIMEOUT" : "UPSTREAM_UNAVAILABLE",
      message: timedOut ? "Apify transcript fallback timed out." : "Apify transcript fallback could not be reached.",
      fallbackAttempted: true,
    };
  }

  if (response.status === 401 || response.status === 403) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "apify:" + APIFY_ACTOR_ID,
      code: "APIFY_AUTH_REQUIRED",
      message: "The configured APIFY_TOKEN was rejected.",
      fallbackAttempted: true,
    };
  }
  if (!response.ok) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "apify:" + APIFY_ACTOR_ID,
      code: "UPSTREAM_UNAVAILABLE",
      message: "Apify transcript fallback returned HTTP " + response.status + ".",
      fallbackAttempted: true,
    };
  }

  let items: unknown;
  try {
    items = await response.json();
  } catch {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "apify:" + APIFY_ACTOR_ID,
      code: "UPSTREAM_PROTOCOL_ERROR",
      message: "Apify returned non-JSON transcript output.",
      fallbackAttempted: true,
    };
  }

  if (!Array.isArray(items) || !items.length || !items[0] || typeof items[0] !== "object") {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "apify:" + APIFY_ACTOR_ID,
      code: "NO_TRANSCRIPT",
      message: "Apify returned no transcript for this video.",
      fallbackAttempted: true,
    };
  }

  const item = items[0] as Record<string, unknown>;
  let segments = normalizeApifySegments(item);
  let text =
    typeof item.fullText === "string"
      ? item.fullText
      : typeof item.transcript_text === "string"
        ? item.transcript_text
        : typeof item.text === "string"
          ? item.text
          : "";

  if (!text && segments.length) text = segments.map((segment) => segment.text).join(" ");
  text = text.replace(/\s+/g, " ").trim();
  if (!segments.length && text) segments = [{ start: 0, duration: 0, text }];

  if (!text) {
    return {
      ok: false,
      source: "youtube",
      videoId,
      provider: "apify:" + APIFY_ACTOR_ID,
      code: "NO_TRANSCRIPT",
      message: "Apify returned an item but it contained no transcript text.",
      fallbackAttempted: true,
    };
  }

  const capped = capTranscript(segments, maxCharacters);
  const selected = item.selected && typeof item.selected === "object"
    ? (item.selected as Record<string, unknown>)
    : undefined;

  return {
    ok: true,
    source: "youtube",
    videoId,
    provider: "apify:" + APIFY_ACTOR_ID,
    language: String(selected?.languageCode ?? item.language ?? language ?? "") || null,
    isAutoGenerated:
      typeof selected?.isGenerated === "boolean"
        ? selected.isGenerated
        : typeof item.is_generated === "boolean"
          ? item.is_generated
          : null,
    text: capped.text,
    segments: capped.segments,
    totalCharacters: capped.totalCharacters,
    truncated: capped.truncated,
  };
}

export function registerVideoTools(server: McpServer, env: VideoEnv) {
  server.registerTool(
    "video.youtube_transcript",
    {
      description:
        "Read the spoken text of a public YouTube video from its available manual or auto-generated captions. Uses direct caption extraction first and an optional Apify fallback when APIFY_TOKEN is configured. It does not download the full video and does not invent speech when captions are unavailable.",
      inputSchema: z.object({
        url: z.string().min(1).max(2_000),
        language: z.string().min(2).max(35).optional(),
        includeTimestamps: z.boolean().optional(),
        maxCharacters: z.number().int().min(1_000).max(HARD_MAX_CHARACTERS).optional(),
      }),
      annotations: {
        readOnlyHint: true,
        idempotentHint: true,
        openWorldHint: true,
        destructiveHint: false,
      },
    },
    async ({ url, language, includeTimestamps, maxCharacters }) => {
      const videoId = parseYoutubeVideoId(url);
      if (!videoId) {
        const failure: TranscriptFailure = {
          ok: false,
          source: "youtube",
          provider: "none",
          code: "INVALID_URL",
          message: "Expected a YouTube watch, youtu.be, shorts, embed, live URL, or an 11-character video ID.",
        };
        return {
          content: [{ type: "text" as const, text: JSON.stringify(failure) }],
          structuredContent: failure,
          isError: true,
        };
      }

      const limit = Math.min(maxCharacters ?? DEFAULT_MAX_CHARACTERS, HARD_MAX_CHARACTERS);
      let result = await directYoutubeTranscript(url, videoId, language, limit);

      if (
        !result.ok &&
        result.code !== "NO_TRANSCRIPT" &&
        result.code !== "INVALID_URL" &&
        env.APIFY_TOKEN
      ) {
        result = await apifyTranscriptFallback(env, url, videoId, language, limit);
      }

      if (!result.ok) {
        if (result.code !== "NO_TRANSCRIPT" && result.code !== "INVALID_URL" && !env.APIFY_TOKEN) {
          result = {
            ...result,
            message: result.message + " Apify fallback is available after configuring APIFY_TOKEN.",
            fallbackAttempted: false,
          };
        }
        return {
          content: [{ type: "text" as const, text: JSON.stringify(result) }],
          structuredContent: result,
          isError: true,
        };
      }

      const output: TranscriptSuccess = includeTimestamps === false
        ? { ...result, segments: undefined }
        : result;

      return {
        content: [{ type: "text" as const, text: output.text }],
        structuredContent: output,
      };
    },
  );
}
